/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Jefferson
 */
public class JDialogProjectScreen extends javax.swing.JDialog {

    /**
     * Creates new form JDialogProjectScreen
     */
    public JDialogProjectScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNewProjectTitle = new javax.swing.JPanel();
        jLabelNewProjectTitle = new javax.swing.JLabel();
        jLabelNewProjectCheck = new javax.swing.JLabel();
        jPanelNewProjectForm = new javax.swing.JPanel();
        jLabelNewProjectNameCab = new javax.swing.JLabel();
        jTextFieldNewProjectName = new javax.swing.JTextField();
        jLabelNewProjectDescriptionCab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNewProjectDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelNewProjectTitle.setBackground(new java.awt.Color(0, 102, 153));

        jLabelNewProjectTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNewProjectTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNewProjectTitle.setText("New Project");

        jLabelNewProjectCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewProjectCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabelNewProjectCheck.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelNewProjectTitleLayout = new javax.swing.GroupLayout(jPanelNewProjectTitle);
        jPanelNewProjectTitle.setLayout(jPanelNewProjectTitleLayout);
        jPanelNewProjectTitleLayout.setHorizontalGroup(
            jPanelNewProjectTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNewProjectCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelNewProjectTitleLayout.setVerticalGroup(
            jPanelNewProjectTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewProjectTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNewProjectCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jLabelNewProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelNewProjectForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNewProjectNameCab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNewProjectNameCab.setText("Name:");

        jTextFieldNewProjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNewProjectName.setToolTipText("");

        jLabelNewProjectDescriptionCab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNewProjectDescriptionCab.setText("Description:");

        jTextAreaNewProjectDescription.setColumns(20);
        jTextAreaNewProjectDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaNewProjectDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNewProjectDescription);

        javax.swing.GroupLayout jPanelNewProjectFormLayout = new javax.swing.GroupLayout(jPanelNewProjectForm);
        jPanelNewProjectForm.setLayout(jPanelNewProjectFormLayout);
        jPanelNewProjectFormLayout.setHorizontalGroup(
            jPanelNewProjectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewProjectFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewProjectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jLabelNewProjectDescriptionCab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNewProjectName)
                    .addComponent(jLabelNewProjectNameCab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelNewProjectFormLayout.setVerticalGroup(
            jPanelNewProjectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewProjectFormLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelNewProjectNameCab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNewProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNewProjectDescriptionCab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNewProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNewProjectForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNewProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNewProjectForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogProjectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogProjectScreen dialog = new JDialogProjectScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNewProjectCheck;
    private javax.swing.JLabel jLabelNewProjectDescriptionCab;
    private javax.swing.JLabel jLabelNewProjectNameCab;
    private javax.swing.JLabel jLabelNewProjectTitle;
    private javax.swing.JPanel jPanelNewProjectForm;
    private javax.swing.JPanel jPanelNewProjectTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNewProjectDescription;
    private javax.swing.JTextField jTextFieldNewProjectName;
    // End of variables declaration//GEN-END:variables
}
